version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: sa
      DB_PASSWORD: P@ssw0rd!
      DB_NAME: CourseW
      DB_PORT: 1434  # Порт на хосте

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"  # Перенаправляем порт 1434 на хосте на порт 1433 внутри контейнера
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd!"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
